// This file will be auto-generated by running: npm run supabase:gen-types
// For now, this is a placeholder with the main table types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          custom_subdomain: string | null
          logo_url: string | null
          plan: 'free' | 'pro' | 'enterprise'
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          subscription_status: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete' | null
          subscription_current_period_end: string | null
          max_users: number
          max_templates: number
          features: Json
          allowed_email_domains: string[]
          default_staff_permissions: Json
          branding_settings: Json | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          name: string
          slug: string
          custom_subdomain?: string | null
          logo_url?: string | null
          plan?: 'free' | 'pro' | 'enterprise'
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete' | null
          subscription_current_period_end?: string | null
          max_users?: number
          max_templates?: number
          features?: Json
          allowed_email_domains?: string[]
          default_staff_permissions?: Json
          branding_settings?: Json | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          custom_subdomain?: string | null
          logo_url?: string | null
          plan?: 'free' | 'pro' | 'enterprise'
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: 'active' | 'trialing' | 'past_due' | 'canceled' | 'incomplete' | null
          subscription_current_period_end?: string | null
          max_users?: number
          max_templates?: number
          features?: Json
          allowed_email_domains?: string[]
          default_staff_permissions?: Json
          branding_settings?: Json | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      users: {
        Row: {
          id: string
          email: string
          full_name: string
          avatar_url: string | null
          org_id: string
          role: 'owner' | 'admin' | 'staff'
          status: 'pending' | 'active' | 'suspended'
          invited_by: string | null
          invited_at: string | null
          accepted_at: string | null
          last_login_at: string | null
          notification_preferences: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name: string
          avatar_url?: string | null
          org_id: string
          role?: 'owner' | 'admin' | 'staff'
          status?: 'pending' | 'active' | 'suspended'
          invited_by?: string | null
          invited_at?: string | null
          accepted_at?: string | null
          last_login_at?: string | null
          notification_preferences?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          avatar_url?: string | null
          org_id?: string
          role?: 'owner' | 'admin' | 'staff'
          status?: 'pending' | 'active' | 'suspended'
          invited_by?: string | null
          invited_at?: string | null
          accepted_at?: string | null
          last_login_at?: string | null
          notification_preferences?: Json
          created_at?: string
          updated_at?: string
        }
      }
      templates: {
        Row: {
          id: string
          org_id: string
          created_by: string
          name: string
          description: string | null
          thumbnail_url: string
          canvas_data: Json
          dimensions: Json
          category: string
          tags: string[]
          is_published: boolean
          is_featured: boolean
          usage_count: number
          last_used_at: string | null
          created_at: string
          updated_at: string
          archived_at: string | null
        }
      }
      projects: {
        Row: {
          id: string
          org_id: string
          user_id: string
          template_id: string | null
          name: string
          thumbnail_url: string | null
          canvas_data: Json
          dimensions: Json
          status: 'draft' | 'completed'
          shared_to_feed: boolean
          shared_at: string | null
          created_at: string
          updated_at: string
        }
      }
      brand_assets: {
        Row: {
          id: string
          org_id: string
          uploaded_by: string
          name: string
          description: string | null
          type: 'logo' | 'image' | 'font' | 'color_palette' | 'icon'
          file_url: string
          thumbnail_url: string | null
          file_size: number
          mime_type: string
          dimensions: Json | null
          color_values: string[] | null
          category: string | null
          tags: string[]
          is_published: boolean
          created_at: string
          updated_at: string
        }
      }
      invitations: {
        Row: {
          id: string
          org_id: string
          email: string
          invited_by: string
          role: 'admin' | 'staff'
          token: string
          expires_at: string
          status: 'pending' | 'accepted' | 'expired' | 'revoked'
          accepted_at: string | null
          accepted_by: string | null
          created_at: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
